import { Metadata } from "next";
import DashboardNav from "@/components/ui/menu/DashboardNav";

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
        <section>
          <DashboardNav />
          {children}
        </section>
    );
  }